### ISSUE TITLE
Cannot find module '@bounce/iframe' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by sisoalbert** [Bounceapp/iframe#145]
**Describe the bug**
"Cannot find module '@bounce/iframe' or its corresponding type declarations.ts(2307)"

**To Reproduce**
Created a new expo app
installed library: npx expo install @bounceapp/iframe react-native-webview
then npm run web
I get that error even though the library is installed and I see it in the package.json

**Expected behavior**
To see a iframe

**Comment by EnzoDeg40** [comment]
Try this
```js
import { Iframe } from "@bounceapp/iframe"
```
